import cadquery as cq

result = (
    cq.Workplane("XY")
    .moveTo(0, 0)
    .rect(10, 50)
    .extrude(5)
    .faces(">Z")
    .workplane()
    .center(-20, 0)
    .rect(10, 50)
    .extrude(5)
    .faces(">Z")
    .workplane()
    .center(0, -20)
    .rect(10, 50)
    .extrude(5)
    .edges("|Z")
    .fillet(2)
    .faces(">Z")
    .workplane()
    .pushPoints([(0, 0), (-20, 0), (0, -20)])
    .hole(5)
)