import cadquery as cq

result = (
    cq.Workplane("XY")
    .center(0, 0)
    .rect(100, 50)
    .extrude(3)
    .faces(">Z")
    .workplane()
    .rect(15, 15, forConstruction=True)
    .vertices()
    .circle(3)
    .extrude(2)
    .faces(">Z")
    .workplane()
    .rect(10, 10)
    .extrude(1)
    .faces(">Z")
    .workplane()
    .rect(20, 20, forConstruction=True)
    .vertices()
    .circle(2)
    .extrude(1)
)