import cadquery as cq

result = (
    cq.Workplane("XY")
    .circle(10)
    .circle(5)
    .extrude(10)
    .faces(">Z")
    .workplane()
    .circle(8)
    .extrude(15)
    .faces(">Z")
    .workplane()
    .circle(6)
    .extrude(5)
    .faces(">Z")
    .workplane()
    .circle(3)
    .extrude(10)
    .faces(">Z")
    .workplane()
    .circle(1.5)
    .extrude(5)
    .faces(">Z")
    .edges()
    .fillet(0.5)
    .faces(">Z")
    .workplane()
    .circle(1)
    .extrude(2)
    .faces(">Z")
    .edges()
    .fillet(1)
)