import cadquery as cq

result = (
    cq.Workplane("XY")
    .box(40, 20, 5)
    .faces(">Z")
    .workplane()
    .center(-10, 0)
    .circle(5)
    .cutThruAll()
    .workplane(offset=5)
    .rect(20, 5)
    .extrude(10)
    .faces(">Z")
    .workplane()
    .center(0, 0)
    .circle(2.5)
    .cutThruAll()
    .faces(">X")
    .workplane(centerOption="CenterOfMass")
    .center(10, 0)
    .circle(7)
    .extrude(10)
    .faces(">Z")
    .workplane(centerOption="CenterOfMass")
    .center(0, 0)
    .circle(3)
    .cutThruAll()
)