import cadquery as cq

result = (cq.Workplane("XY")
          .rect(30, 60)
          .extrude(10)
          .faces(">Z")
          .workplane()
          .transformed(offset=(0, 0, 10))
          .circle(15)
          .cutBlind(-10)
          .edges("|Z")
          .fillet(3)
          .faces("<Z")
          .workplane()
          .transformed(offset=(0, 0, 10))
          .hole(5)
          .faces(">Z")
          .workplane()
          .hole(10)
          .faces(">Z")
          .workplane(centerOption="CenterOfBoundBox")
          .rect(10, 25)
          .cutBlind(-5)
          .faces(">Z")
          .workplane()
          .pushPoints([(-15, 10), (15, 10)])
          .hole(5))