import cadquery as cq

result = (
    cq.Workplane("XY")
    .rect(60, 150)
    .extrude(10)
    .faces(">Z")
    .workplane()
    .rect(40, 80)
    .cutThruAll()
    .faces("<Z")
    .workplane(offset=1)
    .hole(20)
    .faces("<Z")
    .workplane(offset=1)
    .center(-10, 0)
    .hole(3)
    .center(20, 0)
    .hole(3)
    .center(-10, -30)
    .hole(5)
    .edges("|Z")
    .fillet(2)
)