import cadquery as cq
import math

# --- Parameters ---
# Main vertical body dimensions
base_radius = 25.0
main_body_radius = 18.0
main_body_height = 20.0  # Height of the cylindrical part before the dome
dome_radius = main_body_radius

# Flange dimensions
flange_radius = 28.0
flange_thickness = 4.0

# Outlet pipe dimensions
pipe_radius = 10.0
pipe_length = 30.0  # Length from center
pipe_angle_separation = 60.0 # Angle between the two pipes in degrees

# Fillet radius for the intersection
fillet_radius = 3.0

# --- Construction ---

# 1. Base Flange
# Create a cylinder for the bottom flange
flange = cq.Workplane("XY").circle(flange_radius).extrude(flange_thickness)

# 2. Main Central Body (Cylinder + Dome)
# Create the vertical cylinder sitting on the flange
main_cyl = (
    cq.Workplane("XY")
    .workplane(offset=flange_thickness)
    .circle(main_body_radius)
    .extrude(main_body_height)
)

# Create the dome (sphere) on top of the cylinder
dome_center_height = flange_thickness + main_body_height
dome = (
    cq.Workplane("XY")
    .workplane(offset=dome_center_height)
    .sphere(dome_radius)
)

# Cut the bottom half of the sphere so it sits flush (intersect with a box or just rely on union)
# A cleaner way to make a dome on top of a cylinder is to revolve a profile or just union a sphere.
# Since the sphere center is at the top of the cylinder, the bottom half is inside the cylinder.
# We will just union them later.

# 3. Horizontal Pipes
# We need two pipes coming out at an angle.
# Let's orient them symmetrically around the Y-axis for better aesthetics, or X-axis.
# Based on the image, let's assume one is at 0 degrees (X+) and one is angled, 
# or they are symmetric around a central axis.
# Looking at the image, it looks like a "Y" or corner piece. Let's place them at angles relative to X axis.
# Let's assume symmetry around X-axis for simplicity in code logic, then rotate if needed.
# Pipe 1: Angle +30 deg
# Pipe 2: Angle -30 deg (total separation 60 deg)
# Wait, looking closer at the image, one pipe points straight left (let's say -X) 
# and the other points somewhat "back" and left. 
# Let's try: One at 180 degrees (straight left in image view), one at 135 degrees.
# Actually, let's stick to a generic parameter approach.
# Let's model them as cylinders originating from the center (0,0, Z_height)
# The pipes connect to the dome section.

pipe_z_offset = dome_center_height  # Connect at the center of the sphere
# Or slightly lower? The image shows the top of the pipes tangentially blending near the top of the dome.
# Let's align the center of the pipes with the center of the sphere for a "ball joint" look.

def make_pipe(angle_deg):
    angle_rad = math.radians(angle_deg)
    # Direction vector
    dx = math.cos(angle_rad)
    dy = math.sin(angle_rad)
    
    # Create a plane perpendicular to the direction at the end of the pipe
    # Or simpler: create cylinder along X and rotate.
    p = (
        cq.Workplane("YZ")
        .circle(pipe_radius)
        .extrude(pipe_length)
        .translate((0, 0, pipe_z_offset)) # Move up to correct Z
        .rotate((0,0,0), (0,0,1), angle_deg) # Rotate around Z axis
    )
    return p

# Based on the image orientation:
# One pipe looks distinctively parallel to an axis (let's say -X).
# The other comes out at an angle.
pipe1 = make_pipe(180) # Pointing Left
pipe2 = make_pipe(180 - 45) # Pointing "Back-Left" (135 degrees)

# 4. Combine Geometry
# Union everything
part = flange.union(main_cyl).union(dome).union(pipe1).union(pipe2)

# 5. Filleting
# The image shows smooth transitions (fillets) where the pipes meet the main body.
# This is often the trickiest part in CAD kernels.
# We select edges generated by the intersection of the pipes and the main body.
# We look for edges that are roughly at the connection height and intersect the main body radius.

try:
    # Attempt to fillet the specific intersection edges
    # We select edges that are shared by the pipes and the main body.
    # A robust selector is "Edges closest to the connection point"
    
    # Calculate approximate connection points for selection
    conn_x1 = (main_body_radius) * math.cos(math.radians(180))
    conn_y1 = (main_body_radius) * math.sin(math.radians(180))
    
    conn_x2 = (main_body_radius) * math.cos(math.radians(135))
    conn_y2 = (main_body_radius) * math.sin(math.radians(135))

    result = part.edges(
        cq.selectors.NearestToPointSelector((conn_x1, conn_y1, pipe_z_offset))
    ).fillet(fillet_radius)
    
    result = result.edges(
        cq.selectors.NearestToPointSelector((conn_x2, conn_y2, pipe_z_offset))
    ).fillet(fillet_radius)
    
    # Also fillet the transition from main cylinder to flange
    result = result.edges(
        cq.selectors.NearestToPointSelector((main_body_radius, 0, flange_thickness))
    ).fillet(2.0)

except Exception:
    # Fallback if specific edge selection fails, just return the union
    result = part

# Ensure the final object is stored in 'result'
if 'result' not in locals():
    result = part