import cadquery as cq

# --- Parametric Dimensions ---
# Overall dimensions of the main bounding box
total_width = 80.0
total_height = 50.0
total_depth = 40.0

# Central block dimensions
center_block_width = 30.0
center_block_depth = total_depth

# Left wing dimensions
left_wing_width = 25.0
left_wing_height = 20.0
left_wing_depth = 25.0  # Thinner than the main block
left_wing_offset_z = 0.0 # Centered vertically

# Right block dimensions
right_block_width = 25.0
right_block_height = total_height
right_block_depth = total_depth

# Front cutout dimensions
cutout_width = 30.0
cutout_height = 20.0
cutout_depth = 10.0
cutout_fillet_radius = 5.0

# Chamfer dimensions
main_chamfer = 5.0
corner_chamfer = 10.0

# --- Modeling ---

# 1. Create the base central block
# We'll center the design around the origin for easier mirroring if needed, 
# but here we build it up piece by piece.
center_block = cq.Workplane("XY").box(center_block_width, total_depth, total_height)

# 2. Add the Right Block (Full height/depth extension)
right_block = (
    cq.Workplane("XY")
    .center(center_block_width/2 + right_block_width/2, 0)
    .box(right_block_width, right_block_depth, right_block_height)
)

# 3. Add the Left Wing (Thinner, centered vertically)
left_wing = (
    cq.Workplane("XY")
    .center(-(center_block_width/2 + left_wing_width/2), 0)
    .box(left_wing_width, left_wing_depth, left_wing_height)
)

# Combine the main bodies
base_shape = center_block.union(right_block).union(left_wing)

# 4. Create the front cutout
# We select the front face (positive Y direction in default orientation)
# The cutout seems to cut into the central block and the right block slightly
cutout = (
    base_shape.faces(">Y")
    .workplane()
    .center(10, 0) # Offset slightly to the right to match the asymmetry
    .rect(cutout_width, cutout_height)
    .cutBlind(-cutout_depth)
)

# 5. Apply Chamfers
# Look at the image: 
# - There is a large chamfer on the top-right corner.
# - There are smaller chamfers on the front edges of the left wing.

# Large top-right corner chamfer
result = cutout.edges(">X and >Z").chamfer(corner_chamfer)

# Small chamfers on the front face of the left wing
# We select edges that are on the most negative X face, and then filter for the vertical ones
result = result.edges("<X").chamfer(main_chamfer)

# Fillet the inner corners of the cutout
# Select edges that are "inside" the cutout. 
# A robust way is to select vertical edges within a specific X range on the front face.
# Or select edges generated by the last cut operation.
# Here we select vertical edges near the center front
result = result.edges("|Z and >Y").filter(lambda e: e.Center().z < 10 and e.Center().z > -10).fillet(cutout_fillet_radius)


# Return the final result
result = result