import cadquery as cq

result = (cq.Workplane("XY")
          .moveTo(-10, 0)
          .circle(5)
          .moveTo(10, 0)
          .circle(5)
          .extrude(3)
          .faces(">Z")
          .workplane()
          .rect(20, 10)
          .extrude(-3)
          .faces(">Z")
          .workplane()
          .moveTo(-10, 0)
          .circle(2)
          .cutThruAll()
          .moveTo(10, 0)
          .circle(2)
          .cutThruAll())