import cadquery as cq

result = (
    cq.Workplane("XY")
    .rect(60, 20)
    .extrude(10)
    .faces(">Z").workplane()
    .rect(40, 10)
    .extrude(10)
    .faces(">Z").workplane(offset=20)
    .rect(20, 5)
    .extrude(-5)
    .faces(">Z").workplane(centerOption='CenterOfBoundBox')
    .hole(3)
    .faces("<Z").workplane()
    .center(-15, 5)
    .hole(5)
    .center(30, 0)
    .hole(5)
    .faces("<Y").workplane()
    .center(15, 5)
    .hole(5)
    .center(-30, 0)
    .hole(5)
)