import cadquery as cq

result = (
    cq.Workplane("XY")
    .rect(50, 50)
    .extrude(5)
    .faces(">Z")
    .workplane()
    .moveTo(-15, -15)
    .circle(5)
    .cutThruAll()
    .moveTo(15, -15)
    .circle(5)
    .cutThruAll()
    .moveTo(15, 15)
    .circle(5)
    .cutThruAll()
    .moveTo(-15, 15)
    .circle(5)
    .cutThruAll()
    .faces("<Z")
    .workplane()
    .moveTo(0, 0)
    .polyline([(0, 25), (25, 0), (-25, 0)])
    .close()
    .cutBlind(-5)
)  