import cadquery as cq

result = (
    cq.Workplane("XY")
    .box(50, 10, 5)
    .edges("|Z")
    .fillet(1)
    .faces(">Z")
    .workplane(centerOption='CenterOfBoundBox')
    .moveTo(-20, 0)
    .rect(10, 5)
    .cutBlind(-2)
    .moveTo(20, 0)
    .rect(10, 5)
    .cutBlind(-2)
    .faces("<Z")
    .workplane(centerOption='CenterOfBoundBox')
    .moveTo(-20, 0)
    .rect(10, 5)
    .cutBlind(2)
    .moveTo(20, 0)
    .rect(10, 5)
    .cutBlind(2)
)