import cadquery as cq

result = (
    cq.Workplane("XY")
    .box(30, 20, 4)
    .faces(">Z")
    .workplane()
    .center(-15.0, -10.0)
    .box(30, 8, 4, centered=(False, False, False))
    .faces(">Z")
    .workplane()
    .center(15.0, 10.0)
    .circle(4.0)
    .cutThruAll()
    .faces(">Z")
    .workplane()
    .center(-15.0, 0.0)
    .box(30, 8, 4, centered=(False, False, False))
    .faces(">Z")
    .workplane()
    .center(15.0, -10.0)
    .circle(4.0)
    .cutThruAll()
    .faces(">X")
    .workplane()
    .center(-10.0, 15.0)
    .box(4, 20, 8, centered=(False, False, False))
    .faces(">X")
    .workplane()
    .center(10.0, -15.0)
    .circle(4.0)
    .cutThruAll()
    .faces(">X")
    .workplane()
    .center(0.0, -15.0)
    .box(4, 20, 8, centered=(False, False, False))
    .faces(">X")
    .workplane()
    .center(-10.0, 15.0)
    .circle(4.0)
    .cutThruAll()
    .faces(">Y")
    .workplane()
    .center(10.0, -15.0)
    .box(4, 8, 20, centered=(False, False, False))
    .faces(">Y")
    .workplane()
    .center(-10.0, 15.0)
    .circle(4.0)
    .cutThruAll()
    .faces(">Y")
    .workplane()
    .center(-10.0, 0.0)
    .box(4, 8, 20, centered=(False, False, False))
    .faces(">Y")
    .workplane()
    .center(10.0, -15.0)
    .circle(4.0)
    .cutThruAll()
)